---
- name: Update The System Packages
  yum: name=* state=latest update_cache=yes

- name: Ensure NTP (for time synchronization) is installed.
  yum: name=ntp state=present

- name: Install EPEL Repository
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present update_cache=yes

- name: Required Packages
  yum: name={{ item }} state=present
  with_items:
    - nmap
    - net-tools
    - vim
    - wget
    - htop
    - git

- name: Disable SELinux
  selinux:
    state: disabled

- name: Stop Firewall
  service: name=firewalld state=stopped enabled=no